version: '3.4'


services:

  builder: # nazwa serwisu/usługi
    build:
      context: .
      dockerfile: Dockerfile_build
    image: docker_compose_build
    container_name: docker_compose_build_container

  tester: # nazwa serwisu/usługi
    build:
      context: .
      dockerfile: Dockerfile_test
    image: docker_compose_test
    container_name: docker_compose_test_container
    depends_on:
      - builder



# https://docs.docker.com/compose/gettingstarted/
